name: Check PHP Code

on:
  pull_request:
    branches:
      - 5.*-dev
      - 6.*-dev
  push:
    branches:
      - 5.*-dev
      - 6.*-dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  php-compatibility:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check PHP compatibility with PHP 8.3+
        uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: 7.3-
          paths: ${{ github.workspace }}/administrator/language/pl-PL ${{ github.workspace }}/language/pl-PL ${{ github.workspace }}/tests ${{ github.workspace }}/script.php
          extensions: 'php'