name: Translation Test

on:
  pull_request:
    branches:
      - 5.*-dev
      - 6.*-dev
  push:
    branches:
      - 5.*-dev
      - 6.*-dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Composer Installation
        uses: php-actions/composer@v5

      - name: Translation integrity test
        id: test
        uses: php-actions/composer@v5
        with:
          command: "test:translation ${{ github.ref_name }} --ignore-obsolete"
